# Generated by Django 6.0 on 2026-01-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('engagements', '0002_encargo_delete_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('estatus', models.CharField(choices=[('solicitado', 'Solicitado'), ('recibido', 'Recibido'), ('incompleto', 'Incompleto'), ('aprobado', 'Aprobado')], default='solicitado', max_length=20, verbose_name='Estatus')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha compromiso')),
                ('fecha_recibido', models.DateField(blank=True, null=True, verbose_name='Fecha recibido')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('encargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_pbc', to='engagements.encargo', verbose_name='Encargo')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_pbc', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Solicitud PBC',
                'verbose_name_plural': 'Solicitudes PBC',
                'ordering': ['-creado_en'],
            },
        ),
    ]
