# Generated by Django 6.0 on 2026-01-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpbc',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo entregado por el cliente (PDF, Excel, ZIP, etc.)', null=True, upload_to='pbc/', verbose_name='Archivo recibido'),
        ),
    ]
