# Generated by Django 6.0 on 2026-01-07 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbc', '0002_solicitudpbc_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpbc',
            name='archivo',
        ),
        migrations.CreateModel(
            name='DocumentoPBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('archivo', models.FileField(upload_to='pbc/', verbose_name='Archivo')),
                ('nombre', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre (opcional)')),
                ('estatus', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('observado', 'Observado'), ('aprobado', 'Aprobado')], default='recibido', max_length=20, verbose_name='Estatus del documento')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones del auditor')),
                ('subido_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido en')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pbc.solicitudpbc', verbose_name='Solicitud PBC')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pbc', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento PBC',
                'verbose_name_plural': 'Documentos PBC',
                'ordering': ['-subido_en'],
                'constraints': [models.UniqueConstraint(fields=('solicitud', 'version'), name='unique_version_por_solicitud')],
            },
        ),
    ]
