# Generated by Django 6.0.1 on 2026-04-09 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbc', '0003_remove_solicitudpbc_archivo_documentopbc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentopbc',
            name='unique_version_por_solicitud',
        ),
        migrations.AddField(
            model_name='solicitudpbc',
            name='observaciones_revision',
            field=models.TextField(blank=True, default='', help_text='Comentario del auditor para indicar qué falta o qué debe corregirse.', verbose_name='Observaciones de revisión'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='estatus',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('reemplazado', 'Reemplazado')], default='vigente', max_length=20, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pbc.solicitudpbc', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_pbc_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AlterField(
            model_name='documentopbc',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AlterField(
            model_name='solicitudpbc',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('aprobado', 'Aprobado'), ('incompleto', 'Incompleto')], default='pendiente', max_length=20, verbose_name='Estatus'),
        ),
    ]
