# Generated by Django 6.0 on 2026-01-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_type', models.CharField(choices=[('financial', 'Financial'), ('internal', 'Internal'), ('tax', 'Tax'), ('iso', 'ISO'), ('custom', 'Custom')], default='financial', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('execution', 'Execution'), ('closing', 'Closing'), ('issued', 'Issued')], default='planning', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='core.organization')),
            ],
        ),
    ]
