# Generated by Django 6.0 on 2026-01-06 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('financiera', 'Auditoría financiera'), ('interna', 'Auditoría interna'), ('fiscal', 'Auditoría fiscal (SAT)'), ('iso', 'Auditoría ISO'), ('personalizada', 'Personalizada')], default='financiera', max_length=20, verbose_name='Tipo')),
                ('estatus', models.CharField(choices=[('planeacion', 'Planeación'), ('ejecucion', 'Ejecución'), ('cierre', 'Cierre'), ('emitido', 'Emitido')], default='planeacion', max_length=20, verbose_name='Estatus')),
                ('periodo_inicio', models.DateField(verbose_name='Periodo inicio')),
                ('periodo_fin', models.DateField(verbose_name='Periodo fin')),
                ('nombre', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encargos', to='clients.client', verbose_name='Cliente')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encargos', to='core.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Encargo',
                'verbose_name_plural': 'Encargos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.DeleteModel(
            name='Engagement',
        ),
    ]
