# Generated by Django 6.0.1 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_encargo_delete_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='tipo',
            field=models.CharField(choices=[('seguro_social', 'Auditoria para efectos del Seguro Social'), ('impuestos_estatales', 'Auditoria para Impuestos Estatales'), ('gubernamental', 'Auditoria Gubernamental'), ('contabilidad_financiera', 'Contabilidad Financiera'), ('precios_transferencia', 'Precios de Transferencia'), ('asesoria', 'Asesoría'), ('compliance', 'Compliance'), ('seguridad_social', 'Auditoria para efectos de Seguridad Social'), ('impuestos_estatales_2', 'Auditoria de Impuestos Estatales')], default='asesoria', max_length=40, verbose_name='Tipo'),
        ),
    ]
