# Generated by Django 6.0.1 on 2026-04-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_alter_encargo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargo',
            name='tipo',
            field=models.CharField(choices=[('seguro_social', 'Auditoría para efectos del Seguro Social'), ('impuestos_estatales', 'Auditoría de Impuestos Estatales'), ('gubernamental', 'Auditoría Gubernamental'), ('contabilidad_financiera', 'Contabilidad Financiera'), ('precios_transferencia', 'Precios de Transferencia'), ('asesoria', 'Asesoría'), ('compliance', 'Compliance')], default='asesoria', max_length=40, verbose_name='Tipo'),
        ),
    ]
